Controllers/IngredientsController.cs
using System;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.DependencyInjection;
using KTR.Models;
using KTR.ViewModels;
using System.IO;


namespace KTR.Controllers
{
    public class IngredientsController : Controller
    {
        private readonly KTRContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IHostingEnvironment _webroot;

        public IngredientsController(KTRContext context, UserManager<IdentityUser> userManager, IHostingEnvironment webroot)
        {
            _context = context;
            _userManager = userManager;
            _webroot = webroot;
        }


        // *********************************************************************************************************
        //                                         GET: Ingredients Index()
        // *********************************************************************************************************
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var kTRContext = _context.Ingredients.Include(i => i.Recipe);
            return View(await kTRContext.ToListAsync());
        }

        // *********************************************************************************************************
        //                                          GET: Ingredients/Show/5
        // *********************************************************************************************************
        [Authorize]
        public async Task<IActionResult> Show(int? id)
        {
            ViewBag.SavedIngredientId = id;

            if (id == null)
            {
                return NotFound();
            }

            var ingredients = await _context.Ingredients
                .Include(i => i.Recipe)
                .FirstOrDefaultAsync(m => m.IngredientId == id);
            if (ingredients == null)
            {
                return NotFound();
            }

            return View("IngredientsController","ShowIngredients");
        }

        // *********************************************************************************************************
        //                                          GET: Ingredients/Details/5
        // *********************************************************************************************************

        [Authorize]
        public async Task<IActionResult> Details(int? iid)
        {
            ViewBag.SavedIngredientId = iid;

            if (iid == null)
            {
                return NotFound();
            }

            var ingredients = await _context.Ingredients
                .Include(i => i.Recipe)
                .FirstOrDefaultAsync(m => m.IngredientId == iid);
            if (ingredients == null)
            {
                return NotFound();
            }

            return View(ingredients);
        }

        // *********************************************************************************************************
        //                                              GET: Ingredients/Create
        // *********************************************************************************************************

        [Authorize]
        public IActionResult Create(int? id)
        {
            ViewData["RecipeId"] = new SelectList(_context.Recipes, "Id", "Id");
            ViewData["RecipeName"] = (_context.Recipes, "RecipeId", "RecipeName");
            ViewBag.SavedRecipeId = id;
            

            return View();
        }


        // POST: Ingredients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int? id, [Bind("IngredientId,Amt,Unit,Item,Prep,RecipeId,LastUpdated,IRegId,UserId")] Ingredients ingredients)
        {
             ViewBag.SavedRecipeId = id;

            if (ModelState.IsValid)
            {
                _context.Add(ingredients);
                await _context.SaveChangesAsync();
                //return RedirectToAction("ShowRecipes", "Recipes");
                return View();
            }
            ViewData["RecipeId"] = new SelectList(_context.Recipes, "RecipeId", "RecipeName", ingredients.RecipeId);
           // ViewBag.SavedRecipeId = ingredients.RecipeId;
            return View(ingredients);
        }

        // *********************************************************************************************************
        //                                          GET: Ingredients/Edit/5
        // *********************************************************************************************************
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            ViewBag.SavedIngredientId = id;

            if (id == null)
            {
                return NotFound();
            }

            var ingredients = await _context.Ingredients.FindAsync(id);
            if (ingredients == null)
            {
                return NotFound();
            }

            ViewData["RecipeId"] = new SelectList(_context.Recipes, "RecipeId", "RecipeName", ingredients.RecipeId);
            ViewBag.SavedRecipeId = ingredients.RecipeId;
            
            return View(ingredients);
        }

        // *********************************************************************************************************
                                                       // POST: Ingredients/Edit/5
        // *********************************************************************************************************
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IngredientId,Amt,Unit,Item,Prep,RecipeId,LastUpdated,IRegId,UserId")] Ingredients ingredients)
        {
            ViewBag.SavedIngredientId = id;

            if (id != ingredients.IngredientId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ingredients);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!IngredientsExists(ingredients.IngredientId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                // return RedirectToAction(nameof(Index));
                return RedirectToAction("ShowIngredients","ingredients.RecipeId");

            }
            ViewData["RecipeId"] = new SelectList(_context.Recipes, "RecipeId", "RecipeName", ingredients.RecipeId);
            return View(ingredients);

        }

        // *********************************************************************************************************
        //                                          GET: Ingredients/Delete/5
        // *********************************************************************************************************

        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            ViewBag.SavedIngredientId = id;

            if (id == null)
            {
                return NotFound();
            }

            var ingredients = await _context.Ingredients
                .Include(i => i.Recipe)
                .FirstOrDefaultAsync(m => m.IngredientId == id);

            ViewBag.SavedRecipeId = ingredients.RecipeId;

            if (ingredients == null)
            {
                return NotFound();
            }

            return View(ingredients);
        }

        // *********************************************************************************************************
        //                                              POST: Ingredients/Delete/5
        // *********************************************************************************************************

        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ingredients = await _context.Ingredients.FindAsync(id);
            _context.Ingredients.Remove(ingredients);
            await _context.SaveChangesAsync();

            return RedirectToAction("ShowIngredients","ViewBag.SavedRecipeId");
        }

        private bool IngredientsExists(int id)
        {
            return _context.Ingredients.Any(e => e.IngredientId == id);
        }
        // *********************************************************************************************************
        //                                          ShowIngredients()
        //                          Show Users their own ingredients so they can edit them
        // *********************************************************************************************************

        //public async Task<IActionResult> ShowIngredients(int id)
        //{
        //    KTRContext context = new KTRContext();

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KTR</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
   
    <div class="body-content">

        @* This Nav bar appears across all pages using this layout *@
        <nav class="navbar navbar-inverse navbar-fixed-top">

            <div class="grid">
                <div class="wrapper">
                    @*<div class="col-md-12" style="margin:auto">*@
                    <img class="img" src="~/images/KTR_ClipboardBanner.jpg" />
                    @*</div>*@
                </div>
            </div>

            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Kitchen Table Recipes</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        @*<li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li> *@
                        <li><a asp-area="" asp-controller="Recipes" asp-action="Index">Browse Recipes</a></li>
                        <li><a asp-area="" asp-controller="Recipes" asp-action="ShowRecipes">My Recipes</a> </li>
                        @*<li><a asp-area="" asp-controller="Ingredients" asp-action="Index">Ingredients</a></li>
                        <li><a asp-area="" asp-controller="Preparation" asp-action="Index">Prep</a></li>*@
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
        <p> </p>
        <p> </p>
        <p> </p>
        <p> </p>
        <p> </p>
        <p> </p>
        <p> </p>
        <p> </p>

    </div>
    
    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        
           
                <p class="top"> </p> <!-- To make space after adding the banner image. Delete when fixed -->
                <hr />
                @RenderBody()
                <hr style="height: 2px" />
            
        
        <footer >
            <p class="footer">&copy; 2020 - Kitchen Table Recipes</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>