Controllers/RegisterAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using KTR.Models;
using KTR.ViewModels;


namespace KTR.Controllers
{
    public class RegisterAccountController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly KTRContext _context;
       

        public RegisterAccountController(KTRContext context, UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
            
        }


        //Create username and password 
        public IActionResult CreateUser()
        {
            return View();
            //return RedirectToAction("Index", "Recipes");

        }




        //Create account profile
        public IActionResult CreateProfile()
        {
            return View();
            //return RedirectToAction("Index", "Recipes");

        }
        
        /////////////////Create Username and password //////////////////////////////////////
        [HttpPost]
        public IActionResult CreateUser(string username, string password)
        {
            IdentityUser newUser = new IdentityUser();
            newUser.UserName = username;
            newUser.Email = username;

            IdentityResult result = _userManager.CreateAsync(newUser, password).Result;

            if (result.Succeeded)
            {
                _userManager.AddToRoleAsync(newUser, "RegisteredUser").Wait();

                _signInManager.SignInAsync(newUser, false).Wait();
            }

            return RedirectToAction("CreateProfile", "Users");
        }
      
        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
       // [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateProfile([Bind("FName,LName,DisplayName,Email,RegId")] Users user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Recipes));
            }
            return View();
        }

    }

   
}

Views/RegisterAccount/CreateUser.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@model KTR.ViewModels.NewUserViewModel

@{
    ViewData["Title"] = "Create User Account";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="flextop">Create Account</h2>

<!-- <h4>User Profile</h4>  -->
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="RegisterAccount" asp-action="CreateUser">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Username" class="control-label">Email Address</label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConfirmPassword" class="control-label"></label>
                <input asp-for="ConfirmPassword" class="form-control" />
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>


           

            <div class="form-group">
                <input type="submit" value="Register" class="btn btn-success HomeText" />
                <a  asp-controller="Recipes" asp-action="index" class="btn btn-danger HomeText">Cancel</a>
            </div>
        </form>
    </div>
</div>
<!--
<div>
    <a asp-controller="Home" asp-action="Index">Home</a> |
    <a asp-controller="Recipes" asp-action="RecipeList"> Recipes</a>

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
-->