Controllers/PreparationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.DependencyInjection;
using KTR.Models;
using KTR.ViewModels;
using System.IO;

namespace KTR.Controllers
{
    public class PreparationController : Controller
    {
        private readonly KTRContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public PreparationController(KTRContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;

        }

        // **********************************************************************************
        //                            GET: Preparation Index()
        //                                  For Admin
        // **********************************************************************************

        [Authorize(Roles ="Administrator")]
        public async Task<IActionResult> Index()
        {
            var kTRContext = _context.Preparation.Include(p => p.Recipe);
            return View(await kTRContext.ToListAsync());
        }


        // **********************************************************************************
        //                      GET: Preparation MyPrep()
        //                              For users
        // **********************************************************************************

        [Authorize]
        public async Task<IActionResult> MyPrep(int id)
        {
            ViewBag.SavedRecipeId = id;
            string ShowId = _userManager.GetUserId(User);
            var kTRContext = _context.Preparation.Include(p => p.Recipe);


            if (ShowId != null)
            {

                var PrepList = (from p in _context.Preparation
                                  where p.RecipeId == id
                                  orderby p.Step
                                  select p);
                ViewBag.PrepList = PrepList;

                return View(await PrepList.ToListAsync());

            }

            return RedirectToAction("Home");
        }


       


        // GET: Preparation/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            ViewBag.SavedRecipeId = id;

            if (id == null)
            {
                return NotFound();
            }

            var preparation = await _context.Preparation
                .Include(p => p.PReg)
                .Include(p => p.Recipe)
                .FirstOrDefaultAsync(m => m.PrepId == id);
            if (preparation == null)
            {
                return NotFound();
            }

            return View(preparation);
        }

        // ********************************************************************************
        // GET: Preparation/Create
        // ********************************************************************************
        [Authorize]
        public IActionResult Create(int id)
        {
            ViewBag.SavedRecipeId = id;
            ViewData["PRegId"] = new SelectList(_context.AspNetUsers, "Id", "Id");
            ViewData["RecipeId"] = new SelectList(_context.Recipes, "RecipeId", "RecipeName");
            return View();
        }

        // POST: Preparation/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id,[Bind("PrepId,Step,Instr,RecipeId,Updated,PRegId")] Preparation preparation)
        {
            ViewBag.SavedRecipeId = id;

            if (ModelState.IsValid)
            {
                _context.Add(preparation);
                await _context.SaveChangesAsync();
                return RedirectToAction(MyPrep(ViewBag.SavedRecipId));
            }
            ViewData["PRegId"] = new SelectList(_context.AspNetUsers, "Id", "Id", preparation.PRegId);
            ViewData["RecipeId"] = new SelectList(_context.Recipes, "RecipeId", "RecipeName", preparation.RecipeId);
            //return View(preparation);
            return RedirectToAction("MyPrep","ViewBag.SavedRecipId");
        }

        // GET: Preparation/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            ViewBag.SavedPrepId = id;

            if (id == null)
            {
                return NotFound();
            }

            var preparation = await _context.Preparation.FindAsync(id);
            if (preparation == null)
            {
                return NotFound();
            }
            ViewData["PRegId"] = new SelectList(_context.AspNetUsers, "Id", "Id", preparation.PRegId);
            ViewData["RecipeId"] = new SelectList(_context.Recipes, "RecipeId", "RecipeName", preparation.RecipeId);

            ViewBag.SavedRecipeId = preparation.RecipeId;

            return View(preparation);
        }

        // POST: Preparation/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PrepId,Step,Instr,RecipeId,Updated,PRegId")] Preparation preparation)
        {
            ViewBag.SavedRPrepId = id;

            if (id != preparation.PrepId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(preparation);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PreparationExists(preparation.PrepId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                ViewBag.SavedRecipeId = preparation.RecipeId;
                return RedirectToAction("MyPrep",ViewBag.SavedRecipeId);
            }
            ViewData["PRegId"] = new SelectList(_context.AspNetUsers, "Id", "Id", preparation.PRegId);
            ViewData["RecipeId"] = new SelectList(_context.Recipes, "RecipeId", "RecipeName", preparation.RecipeId);
            return View(preparation);
        }

        // GET: Preparation/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            ViewBag.SavedPrepId = id;

            //if (id == null)
            //{
            //    return NotFound();
            //}

            var preparation = await _context.Preparation
               .FirstOrDefaultAsync(m => m.PrepId == id);

            //var preparation = await _context.Preparation
            //    .Include(p => p.PReg)
            //    .Include(p => p.Recipe)
            //    .FirstOrDefaultAsync(m => m.PrepId == id);
            if (preparation == null)
            {
                return NotFound();
            }

            ViewBag.SavedRecipeId = preparation.RecipeId;
            //return View(preparation);
            return RedirectToAction("MyPrep", ViewBag.SavedRecipeId);
        }

        // POST: Preparation/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var preparation = await _context.Preparation.FindAsync(id);
            _context.Preparation.Remove(preparation);
            await _context.SaveChangesAsync();

            ViewBag.SavedRecipeId = preparation.RecipeId;
            // return RedirectToAction(nameof(Index));
            return RedirectToAction("MyPrep", ViewBag.SavedRecipeId);
        }

        private bool PreparationExists(int id)
        {
            return _context.Preparation.Any(e => e.PrepId == id);
        }
    }
}

Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using KTR.Models;
using KTR.ViewModels;

namespace KTR.Controllers
{
    public class UsersController : Controller
    {
        private readonly KTRContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public UsersController(KTRContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;

        }

        // *********************************************************************************************************
        //                                          GET: Users
        // *********************************************************************************************************
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Users.ToListAsync());
        }

        // GET: Users/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var users = await _context.Users
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (users == null)
            {
                return NotFound();
            }

            return View(users);
        }

        // *********************************************************************************************************
        //                                      GET: UserProfile/Create User Profile
        // *********************************************************************************************************
        [Authorize]
        public IActionResult CreateProfile()
        {
            return View();
        }


        // *********************************************************************************************************
        //                                          GET: Users/Create User Login
        // *********************************************************************************************************
        
        public IActionResult CreateUser()
        {
            return View();
        }
        // *********************************************************************************************************
        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        // *********************************************************************************************************
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateUser([Bind("UserId,Fname,Lname,Email,DisplayName,RegId")] Users users)
        {
            if (ModelState.IsValid)
            {
                _context.Add(users);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Recipes");
            }
            return View(users);
        }

        // *********************************************************************************************************
        // POST: Users/CreateProfule
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        // *********************************************************************************************************
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateProfile([Bind("UserId,Fname,Lname,Email,DisplayName,RegId")] Users users)
        {
            if (ModelState.IsValid)
            {
                _context.Add(users);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Recipes");
                //return RedirectToAction(nameof(Recipes));
            }
            return View(users);
        }

        

        // *********************************************************************************************************
        //                                              GET: Users/Edit/5  
        // *********************************************************************************************************

        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            var CurrentUserId = _userManager.GetUserId(User);
            var CurrentUserName = _userManager.GetUserName(User);

            if (CurrentUserId == "URegId")
            {

                //action goes here
                 if (id == null)
                 {
                        return NotFound();
                  }

                var users = await _context.Users.FindAsync(id);
                    if (users == null)
                     {
                     return NotFound();
                     }

                return View(users);
            }
            if (CurrentUserName == "admin@ktr.com")
                {
                    //same action here
                    if (id == null)
                    {
                        return NotFound();
                    }

                    var users = await _context.Users.FindAsync(id);
                    if (users == null)
                    {
                        return NotFound();
                    }

                    return View(users);
              }

            return NotFound();



        }





        // *********************************************************************************************************
        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        // *********************************************************************************************************
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,Fname,Lname,Email,DisplayName")] Users users)
        {
            if (id != users.UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(users);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsersExists(users.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(users);
        }

        // *********************************************************************************************************
        //                                                  GET: Users/Delete/5
        // *********************************************************************************************************

        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var users = await _context.Users
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (users == null)
            {
                return NotFound();
            }

            return View(users);
        }

        // *********************************************************************************************************
        //                                      POST: Users/Delete/5
        // *********************************************************************************************************
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var users = await _context.Users.FindAsync(id);
            _context.Users.Remove(users);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UsersExists(int id)
        {
            return _context.Users.Any(e => e.UserId == id);
        }
    }
}

Views/Recipes/AdminCreate.cshtml
@model KTR.Models.Recipes

@{
    ViewData["Title"] = "Admin Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="flextop">Admin View Create New Recipe</h2>

<h4>
    Creating recipe on behalf of: User  @ViewBag.SavedUserId (@ViewBag.RegNum)
     
</h4>
<p> Note: If the above line doesn't have the user id number, go to the <a asp-controller="Users" asp-action="Index">user list</a> and start this process from there. </p>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AdminCreate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RecipeName" class="control-label"></label>
                <input asp-for="RecipeName" class="form-control" />
                <span asp-validation-for="RecipeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" value="@ViewBag.SavedUserId" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Servings" class="control-label"></label>
                <input asp-for="Servings" class="form-control" />
                <span asp-validation-for="Servings" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class ="form-control" asp-items="ViewBag.CategoryId"></select>
            </div>
            <div class="form-group">
                <label asp-for="StatusId" class="control-label"></label>
                <select asp-for="StatusId" class ="form-control" asp-items="ViewBag.StatusId"></select>
            </div>
            <div class="form-group">
                <label asp-for="MainId" class="control-label"></label>
                <select asp-for="MainId" class ="form-control" asp-items="ViewBag.MainId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhotoPath" class="control-label"></label>
                <input asp-for="PhotoPath" class="form-control" />
                <span asp-validation-for="PhotoPath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegId" class="control-label"></label>
                <input asp-for="RegId" class="form-control" value="@ViewBag.RegNum" />
                <span asp-validation-for="RegId" class="text-danger"></span>
                
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success HomeText" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to Recipe List</a>
</div>

Views/Recipes/AdminEdit.cshtml
@model KTR.Models.Recipes

@{
    ViewData["Title"] = "Admin Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="flextop">Edit User Recipe</h2>

<h4> @Html.DisplayFor(model => model.RecipeName)  </h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AdminEdit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="RecipeId" />
            <div class="form-group">
                <label asp-for="RecipeName" class="control-label"></label>
                <input asp-for="RecipeName" class="form-control" />
                <span asp-validation-for="RecipeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select readonly="readonly" asp-for="UserId" class="form-control" asp-items="@ViewBag.UserId" ></select>
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Servings" class="control-label"></label>
                <input asp-for="Servings" class="form-control" />
                <span asp-validation-for="Servings" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StatusId" class="control-label"></label>
                <select asp-for="StatusId" class="form-control" asp-items="ViewBag.StatusId"></select>
                <span asp-validation-for="StatusId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastUpdated" class="control-label"></label>
                <input  readonly="readonly"  asp-for="LastUpdated" class="form-control" value="@DateTime.Now" type="datetime"  /> 
                <span asp-validation-for="LastUpdated" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MainId" class="control-label"></label>
                <select asp-for="MainId" class="form-control" asp-items="ViewBag.MainId"></select>
                <span asp-validation-for="MainId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhotoPath" class="control-label"></label>
                <input asp-for="PhotoPath" class="form-control" />
                <span asp-validation-for="PhotoPath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegId" class="control-label"></label>
                <input readonly="readonly"  asp-for="RegId" class="form-control" />
                <span asp-validation-for="RegId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success HomeText" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Recipes/AdminIndex.cshtml
@model IEnumerable<KTR.Models.Recipes>
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager


@{
    ViewData["Title"] = "Recipes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2 class="flextop">Admin View - All Recipes</h2>

<p>
    <a asp-controller="Recipes" asp-action="AdminCreate">Create New Recipe</a> | <a asp-controller="Users" asp-action="Index">View Users </a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RecipeName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Servings)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.LastUpdated)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.CategoryId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MainId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StatusId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserId)
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)

        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.RecipeName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Servings)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastUpdated)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.CatName.CatName)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.MainName.MainName)
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.StatusId)*@
                    @Html.DisplayFor(modelItem => item.StatusName.StatusName)
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.UserId)*@
                    @Html.DisplayFor(modelItem => item.UserId)
                </td>
                <td>
                    | <a asp-action="Details" asp-route-id="@item.RecipeId">Details</a> |
                    <a asp-action="AdminEdit" asp-route-id="@item.RecipeId">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@item.RecipeId">Delete</a>
                </td>
            </tr>

        }
    </tbody>
</table>

@*<a asp-controller= "Recipes" asp-action="ShowRecipes">Show My Recipes</a>*@

Views/Recipes/Delete.cshtml
@model KTR.Models.Recipes


@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="flextop">Delete Recipe:  @Html.DisplayFor(model => model.RecipeName)</h2>

<h3>
    Are you sure you want to delete the recipe "@Html.DisplayFor(model => model.RecipeName)"?
    <br />
    You cannot undo this action.
</h3>
<div class="col-md-12">
    Note: You must delete any ingredients and instructios associated with the recipe prior to deleting the recipe. 
</div>
<div>
    @*<h4>Recipes</h4>*@
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RecipeName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RecipeName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Servings)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Servings)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastUpdated)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastUpdated)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CategoryId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CatName.CatName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MainId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MainName.MainName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.StatusId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StatusName.StatusName) 
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.User) Id
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="RecipeId" />
        <input type="submit" value="Delete" class="btn btn-danger HomeText" /> 
        <a asp-action="ShowRecipes"  class="btn btn-info HomeText">Back to List</a>
    </form>
</div>

Views/Recipes/Details.cshtml
@model KTR.Models.Recipes
@using Microsoft.AspNetCore.Identity;
@inject UserManager<IdentityUser> userManager


@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="flextop"> @Html.DisplayFor(model => model.RecipeName)</h2>

<hr />
<div>
    <h4>Recipe Details</h4>
    <a asp-action="Edit" asp-route-id="@Model.RecipeId">Edit Recipe Details</a>

    <dl class="dl-horizontal">
        <dt>
            @*@Html.DisplayNameFor(model => model.PhotoPath)*@
        </dt>
        <dd>
            <img src="/FoodPhotos/@Html.DisplayFor(model => model.PhotoPath)"  width="125" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RecipeName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RecipeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Servings)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Servings)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategoryId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CatName.CatName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MainId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MainName.MainName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StatusId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StatusName.StatusName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            <!--  @Html.DisplayNameFor(model => model.LastUpdated) --> Last Updated
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastUpdated)
        </dd>
               

    </dl>
</div>
<div>

    <a class="btn btn-info HomeText" asp-controller="Ingredients" asp-action="ShowIngredients" asp-route-id="@Model.RecipeId">View Ingredient List</a>
    <a class="btn btn-info HomeText" asp-controller="Preparation" asp-action="MyPrep" asp-route-id="@Model.RecipeId"> View Recipe Instructions  </a>
    <br /><br />
    <a asp-action="ShowRecipes">Back to My Recipe List</a>

</div>